spring:
  datasource:
    url: jdbc:postgresql://db:5432/rinha
    username: admin
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

logging:
  level:
    root: ERROR
